version: '3.8'

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: node:20-slim
    env_file: .env
    working_dir: /app
    command: "node dist/index.js" 
    volumes: 
      - ./backend:/app
    ports:
      - "5001:5001"

  install-deps:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: "npm i"
    profiles:
      - manual

